###### RECIPES ######
build:
  cargo build --release
  #cargo build

# Finds the last-built application file
find-last-built-app-elf:
  #!/usr/bin/env bash
  find ./target/ -maxdepth 3 -name "app" -type f -printf "%A@ %p\n" | sort -r | head -n1 | cut -d' ' -f2

# Runs objdump with nice colours
objdump *ARGS="-d":
  #!/usr/bin/env bash
  ULP_ELF="$(just find-last-built-app-elf)"
  riscv32-esp-elf-objdump --demangle=rust  --visualize-jumps=extended-color --disassembler-color=extended "${ULP_ELF}" {{ARGS}}

###### LINTING ######

cargo-format:
  #!/usr/bin/env bash
  shopt -s globstar 
  cargo fmt --all -- --config-path=rustfmt.toml src/**/*.rs

cargo-clippy:
  #!/usr/bin/env bash
  cargo clippy -- -D warnings --no-deps
