# ulp-blinky

# Set recipe parameters
chip := "esp32s3"
target := "riscv32imc-unknown-none-elf"

bin_name := "app"
bin_arch := "riscv32-esp-elf"

# Import common recipes
set allow-duplicate-variables
import "../../binutils.just"
import "../../clippy.just"

default:
  just build

# Build the crate and generate linker script
build CHIP=chip:
  #!/usr/bin/env bash
  set -eou pipefail
  cargo {{CHIP}}
  ecode="$?"
  app_file="$(just find-last-built-app-elf)"
  # NEW 2026-05-13
  #   No longer using scripts to build the shared linker script.
  #   Instead, uses the '../shared/' crate binary to do this.
  # Step 1. Get base address for CHIP
  chip_base_addr="$(just get-chip-base-address {{CHIP}})"
  # Step 2. Build linker script for app
  just build-linker-script "${app_file}" "${chip_base_addr}"

# USAGE: just build-linker-script
# Runs the shared CLI tool to extract global variables from the ULP ELF,
# and save them to a linker script co-located with the ELF file.
[private]
build-linker-script ELF BASE_ADDRESS:
  #!/usr/bin/env bash
  # Save absolute paths to the input file
  app_file="$(realpath {{ELF}})"
  # The output file is the same as the input, with the '.x' suffix.
  out_file="${app_file%.*}.x"
  # navigate to teh shared crate
  mydir="{{justfile_directory()}}"
  shared_crate="${mydir}/../shared/"
  pushd "${shared_crate}"
  # Extract the symbols, adding base address
  just cli -f "${app_file}" -l -b {{BASE_ADDRESS}} | tee "${out_file}"
  ecode="$?"
  # Exit directory
  popd
  # Return result
  exit "${ecode}"

# USAGE: just get-chip-base-address CHIP
# RETURNS: 0x50000000 for esp32s3/esp32s2, else 0x60000000 for esp32c6
[private]
get-chip-base-address CHIP:
  #!/usr/bin/env python3
  chips = {}
  chips |= {"esp32s3" : 0x50000000}
  chips |= {"esp32s2" : 0x50000000}
  chips |= {"esp32c6" : 0x60000000}
  chip_key = "{{CHIP}}".lower().strip().lstrip()
  chip_addr = chips[chip_key]
  # format as hex
  print(hex(chip_addr)) 