# ulp-blinky

# Set recipe parameters
chip := "esp32s3"
target := "riscv32imc-unknown-none-elf"

bin_name := "app"
bin_arch := "riscv32-esp-elf"

# Import common recipes
set allow-duplicate-variables
import "../../binutils.just"
import "../../clippy.just"

default:
  just build

build:
  #!/usr/bin/env bash
  set -e
  cargo {{chip}}
  app_file="$(just find-last-built-app-elf)"
  just build-shared-linkscript <(just extract-shared-symbols) "${app_file%.*}.x"

extract-shared-symbols ELF=`just find-last-built-app-elf`:
  #!/usr/bin/env bash
  # objcopy to a tempfile, to get only the data in .ulp section. then nm that object to produce a shared mem list.
  outa="$(mktemp)"
  outf="$(mktemp)"
  riscv32-esp-elf-objcopy -j .ulp {{ELF}} "${outf}" 2>/dev/null && \
  riscv32-esp-elf-nm --demangle=rust -n "${outf}" >"${outa}" && \
  cat "${outa}" && \
  rm -f "${outa}" && \
  rm -f "${outf}"

[private]
build-shared-linkscript INFILE OUTFILE:
  #!/usr/bin/env python3
  # Parses an input .syms file, which should contain the result of 'riscv32-esp-elf-nm -n --demangle=rust ...'.
  # Prodices an .ld file which can be used by the esp32s3 program to compile against.
  infile = "{{INFILE}}"
  outfile = "{{OUTFILE}}"
  base_addr = 0x50000000 # address in ESP32S3
  # Parse the symbols, which are in address,type,name format.
  symlist = []
  with open(infile,"r") as f:
    for l in f.readlines():
      addr,kind,name = l.split(" ",3)
      new_addr = hex(base_addr + int(addr,16))
      if kind == 'D': # data 
        new_name = f".ulp.{name.strip().lstrip()}"
      elif kind == 'A': # address
        new_name = f"{name.strip().lstrip()}"
      symlist.append((new_addr,new_name,kind))
  with open(outfile,"w") as f:
    f.write("SECTIONS {\n")
    for (a,n,k) in symlist:
      if k == 'A':
        # address 
        f.write(f"  PROVIDE({n} = {a});\n")
      elif k == 'D':
        # data
        f.write(f"  {n} {a} (NOLOAD):\n")
        f.write("  {\n")
        f.write(f"    *({n})\n")
        f.write("  }\n")
    f.write("}\n")