# hp-blinky

## Set recipe parameters
chip := "esp32s3" 
target := "xtensa-esp32s3-none-elf"
ulp_app_crate := "../ulp-app-main/"  

# binutils.just params
bin_name := "example-esp32s3"
bin_arch := "xtensa-esp-elf"

# custom params
test_elf_name := "integration"

# Import common recipes
set allow-duplicate-variables
set allow-duplicate-recipes
import "../../binutils.just"
import "../../clippy.just"
import "../../hp_crate.just"


test *ARGS="": prepare
  #!/usr/bin/env bash
  # Runs all tests, even if they fail
  cargo test --release --target xtensa-esp32s3-none-elf --features esp32s3 --test integration {{ARGS}}
  # Run a specific test 
  #cargo test --release --target xtensa-esp32s3-none-elf --features esp32s3 --test integration ulp_can_change_timer_period
  # Runs all tests, even if they fail
  #cargo test --target xtensa-esp32s3-none-elf --features esp32s3 --no-fail-fast

example: prepare
  #!/usr/bin/env bash
  # Flash the regular binary, doesnt perform any testing, but confirms that the ULP code is working!
  cargo build --release --target xtensa-esp32s3-none-elf --features esp32s3,println --bin example-esp32s3
  just flash && just monitor

prepare:
  #!/usr/bin/env bash
  set -eou pipefail
  # Build the ULP core application, and copy it over to here
  just build-ulp-app {{ulp_app_crate}} {{chip}}

# OVERRIDES this recipe in binutils
find-last-built-app-elf:
  #!/usr/bin/env bash
  just find-last-built-test-elf

# Finds the last-built test suite application,
# as would be used by probe-rs
find-last-built-test-elf:
    #!/usr/bin/env bash
    set +eou pipefail
    # This uses regex to find the app, while excluding the .d lib file :)
    search_results=$(find ./target/ -maxdepth 5 -regextype sed -regex '.*/{{test_elf_name}}-\w*' -type f -printf "%A@ %p\n")
    elf_path="$(echo ${search_results} | sort -r | head -n1 | cut -d' ' -f2)"
    realpath "${elf_path}"
