# hp-blinky

## Set recipe parameters
chip := "esp32s3" 
target := "xtensa-esp32s3-none-elf"
ulp_app_crate := "../ulp-app-main/"  

# binutils.just params
bin_name := "app"
bin_arch := "xtensa-esp-elf"

# Import common recipes
set allow-duplicate-variables
import "../../binutils.just"
import "../../clippy.just"
import "../../hp_crate.just"

default:
  just build-ulp-app {{ulp_app_crate}} {{chip}}
  cargo run --target xtensa-esp32s3-none-elf --features unstable,defmt,esp32s3 --bin main
  #cargo run --target xtensa-esp32s3-none-elf --features unstable,esp32s3 --bin simple
