[target.'cfg(target_arch = "riscv32")']
runner    = "probe-rs run --preverify"
rustflags = [
    "--cfg", "embedded_test",

    "-C", "link-arg=-Tembedded-test.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "probe-rs run --preverify"
rustflags = [
    "--cfg", "embedded_test",

    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tembedded-test.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "link-arg=-Wl,-Tlinkall.x",
]

[env]
DEFMT_LOG = "info,embedded_test=warn"

[unstable]
build-std = ["core", "alloc"]

[net]
git-fetch-with-cli = true

#[alias]
#esp32c6 = "build --release --features=esp32c6 --target riscv32imac-unknown-none-elf"
#esp32s2 = "build --release --features=esp32s2 --target xtensa-esp32s2-none-elf"
#esp32s3 = "build --release --features=esp32s3 --target xtensa-esp32s3-none-elf"