[alias]
esp32s3 = "build --features esp32s3 --release --target riscv32imc-unknown-none-elf"
esp32c6 = "build --features esp32c6 --release --target riscv32imac-unknown-none-elf"

[build]
target = "riscv32imac-unknown-none-elf" # ESP32-C6
#target = "riscv32imc-unknown-none-elf"  # ESP32-S2 + ESP32-S3

[target.'cfg(target_arch = "riscv32")']
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[unstable]
build-std = ["core"]
