# hp-blinky

## Set recipe parameters
chip := "esp32s3" 
target := "xtensa-esp32s3-none-elf"

# binutils.just params
bin_arch := "xtensa-esp-elf"

# custom params
test_elf_name := "integration"

# Import common recipes
set allow-duplicate-variables
set allow-duplicate-recipes
import "../binutils.just"
import "../clippy.just"

test *ARGS="": prepare
  #!/usr/bin/env bash
  cargo test --target xtensa-esp32s3-none-elf --features esp32s3 --test integration {{ARGS}}

# Build the test binary, to run manually with probe-rs.
# Symlink the test binary to hp_test.elf
build *ARGS="": prepare
  #!/usr/bin/env bash
  set -eou pipefail
  cargo build --target xtensa-esp32s3-none-elf --features esp32s3 --test integration
  elf_path="$(just find-last-built-app-elf)"
  ln -srf "${elf_path}" ./hp_test.elf

[private]
prepare:
  #!/usr/bin/env bash
  set -eou pipefail
  # Build the ULP core application(s), and copy it over to here
  just build-ulp-app ../lp-app/ {{chip}}
  just build-ulp-app ../lp-ws2812-app/ {{chip}}

# Enters the ulp project, and builds it.
[private]
build-ulp-app APPCRATE CHIP:
  #!/usr/bin/env bash
  set -eou pipefail
  # Move into the ULP/LP app crate directory
  appdir="$(realpath {{APPCRATE}})"
  pushd "${appdir}" >/dev/null
  # NEW 2026-05-13
  # Use 'just build CHIP' in the ULP crate,
  # which allows it to perform other linker-script generating steps,
  # if necessary.
  just build {{CHIP}}
  ecode="$?"
  # Get the absolute path to the built ELF,
  # and return to the HP crate directory
  appfile="$(just find-last-built-app-elf)"
  # Extract the name part of the built app
  appname="$(just crate-binary-name)"
  popd >/dev/null
  # Copy the built application to lp_app
  outfile="$(realpath ./)/${appname}"
  cp "${appfile}" "${outfile}"
  test -f "${appfile%.*}.x" && cp "${appfile%.*}.x" "${outfile}.x"
  exit $ecode

[private]
find-last-built-app-elf:
  #!/usr/bin/env bash
  set -eou pipefail
  # This uses regex to find the app, while excluding the .d lib file :)
  search_results=$(find ./target/ -maxdepth 5 -regextype sed -regex '.*/{{test_elf_name}}-\w*' -type f -printf "%A@ %p\n")
  elf_path="$(echo ${search_results} | sort -r | head -n1 | cut -d' ' -f2)"
  realpath "${elf_path}"
