# hp-blinky

## Set recipe parameters
chip := "esp32s3" 
target := "xtensa-esp32s3-none-elf"

# binutils.just params
bin_arch := "xtensa-esp-elf"

# custom params
test_elf_name := "integration"
example_name := "hp_deepsleep_wakeup"

# Import common recipes
set allow-duplicate-variables
set allow-duplicate-recipes
import "../binutils.just"
import "../clippy.just"

# Run HP-LP integration tests with probe-rs
test *ARGS="": prepare
  #!/usr/bin/env bash
  cargo test --target xtensa-esp32s3-none-elf --features esp32s3 --test integration {{ARGS}}

# Build the test binary, to run manually with probe-rs.
# Symlinks the test binary to hp_test.elf
build *ARGS="": prepare
  #!/usr/bin/env bash
  set -eou pipefail
  cargo build --target xtensa-esp32s3-none-elf --features esp32s3 --test integration
  elf_path="$(just find-last-built-test-elf)"
  ln -srf "${elf_path}" ./hp_test.elf

[private]
be EXAMPLE *ARGS="":
  #!/usr/bin/env bash
  cargo build --target xtensa-esp32s3-none-elf --features esp32s3,println,unstable,defmt --example {{EXAMPLE}} {{ARGS}}
  # Symlink the compiled ELF for easier debugging
  elf_path="$(just find-last-built-app-elf {{EXAMPLE}})"
  ln -srf "${elf_path}" ./{{EXAMPLE}}.elf

# Build all examples and symlink them into the root
build-examples: prepare
  #!/usr/bin/env bash
  just be hp_deepsleep_wakeup
  just be hp_gpio_wakeup
  just be hp_print_rtcio_interrupts
  just be hp_ipc_locks

# Build and run an example
example EXAMPLE=example_name: prepare
  #!/usr/bin/env bash
  # For some reason the .cargo link flags aren't passing through to the crate binaries reliably.
  #export RUSTFLAGS="-Clink-arg=-nostartfiles -Clink-arg=-Tdefmt.x -Clink-arg=-Wl,-Tlinkall.x -Clink-arg=-Wl,-Tlp_rainbow.x"
  cargo run --target xtensa-esp32s3-none-elf --features esp32s3,println,unstable,defmt --example {{EXAMPLE}}

[private]
prepare:
  #!/usr/bin/env bash
  set -eou pipefail
  # Build the ULP core application(s), and copy it over to here
  just build-ulp-app ../lp-app/ {{chip}}
  just build-ulp-app ../lp-ws2812-app/ {{chip}}

# Enters the ulp project, and builds it.
[private]
build-ulp-app APPCRATE CHIP:
  #!/usr/bin/env bash
  set -eou pipefail
  # Move into the ULP/LP app crate directory
  appdir="$(realpath {{APPCRATE}})"
  pushd "${appdir}" >/dev/null
  # NEW 2026-05-13
  # Use 'just build CHIP' in the ULP crate,
  # which allows it to perform other linker-script generating steps,
  # if necessary.
  just build {{CHIP}}
  ecode="$?"
  # Get the absolute path to the built ELF,
  # and return to the HP crate directory
  appfile="$(just find-last-built-app-elf)"
  # Extract the name part of the built app
  appname="$(just crate-binary-name)"
  popd >/dev/null
  # Copy the built application to lp_app
  outfile="$(realpath ./)/${appname}"
  cp "${appfile}" "${outfile}"
  test -f "${appfile%.*}.x" && cp "${appfile%.*}.x" "${outfile}.x"
  exit $ecode

find-last-built-test-elf:
  #!/usr/bin/env bash
  set -eou pipefail
  # This uses regex to find the app, while excluding the .d lib file :)
  search_results=$(find ./target/ -maxdepth 5 -regextype sed -regex '.*/{{test_elf_name}}-\w*' -type f -printf "%A@ %p\n")
  elf_path="$(echo ${search_results} | sort -r | head -n1 | cut -d' ' -f2)"
  realpath "${elf_path}"

# Stream the serial port to stdout, and
# auto-reconnect if the port disappears.
monitor PORT="/dev/ttySTOMP*":
  #!/usr/bin/env bash
  while [ true ]; do
    test -c {{PORT}} && just try-stream {{PORT}}
    # if exit with Ctrl-C, return code will be 130.
    # this should cause a break in the loop
    if [ "$?" -eq 130 ];
    then
      break
    fi
  done

[private]
try-stream PORT:
  #!/usr/bin/env bash
  echo "# [$(date +%s)] Connected to {{PORT}}"
  while [ true ]; do
    stty -F {{PORT}} speed 115200 cs8 -cstopb -parenb -echo time 3 min 0 >/dev/null 2>&1 && break
    sleep 0.01
  done

  while [ true ]; do
    cat {{PORT}} 2>/dev/null || break
  done
  echo "# [$(date +%s)] Disconnected from {{PORT}}"

format:
  #!/usr/bin/env bash
  shopt -s globstar 
  cargo fmt --all -- --config-path=rustfmt.toml src/*.rs
  cargo fmt --all -- --config-path=rustfmt.toml examples/*.rs
  cargo fmt --all -- --config-path=rustfmt.toml tests/*.rs
