###### Parameters ######
# chip - The ESP32 chip to target, for both HP and LP crates.
# A cargo alias must be added to both crates,
# which matches the name of this chip,
# and calls `cargo build`. For example:
# [alias]
# esp32s3 = "build --release --features=esp32s3 --target xtensa-esp32s3-none-elf"
chip := "esp32s3" 

# hp_app_crate - The crate containing the HP core project.
hp_app_crate := "./"  

# ulp_app_crate - The crate containing the ULP project.
# This will be built using the command `cargo {{chip}}`,
# which must be aliased in the `.cargo/config.toml` of the ULP project.
ulp_app_crate := "../ulp-baremetal/"  

# ulp_app_name - The name of the ULP ELF file, when ulp_app_crate is built.
ulp_app_name := "blinky"

# espflash_flags - Extra arguments to use when flashing the HP core.
espflash_flags := "--no-skip --ignore_app_descriptor --partition-table ./partitions.csv"

###### RECIPES ######

[doc('build, flash, and monitor')]
all:
  @just build && just flash && just monitor 

[doc('Build LP & HP crates')]
build HPAPP=hp_app_crate ULPAPP=ulp_app_crate CHIP=chip:
  #!/usr/bin/env bash
  set +eu pipefail
  just build-ulp-app {{ULPAPP}} {{CHIP}}
  just build-hp-app {{HPAPP}} {{CHIP}}

# Builds crate located at APPCRATE, for CHIP, using 'cargo {{CHIP}}' alias.
[private]
build-hp-app APPCRATE CHIP:
  #!/usr/bin/env bash
  set +eu pipefail
  appdir="$(realpath {{APPCRATE}})"
  pushd "${appdir}" >/dev/null
  cargo {{CHIP}}
  popd >/dev/null

# Enters the ulp project, and builds it.
# A cargo alias for 'cargo {{CHIP}}', must be added to `.cargo/config.toml`, in the ULP project.
[private]
build-ulp-app APPCRATE CHIP:
  #!/usr/bin/env bash
  set +eu pipefail
  appdir="$(realpath {{APPCRATE}})"
  outdir="$(realpath ./ulp-apps/)"
  pushd "${appdir}" >/dev/null
  cargo {{CHIP}}
  appfile="${appdir}/$(just find-last-built-app-elf)"
  popd >/dev/null
  # Copy the built application to built_ulp_apps
  appfile="$(realpath "${appfile}")"
  # appname="$(basename "${appfile}")"
  # outname="{{CHIP}}-ulp-${appname}"
  outname="{{CHIP}}-ulp-{{ulp_app_name}}"
  cp -v "${appfile}" "${outdir}/${outname}"

# Repeatedly attempts to flash until successful
flash APPFILE=`just find-last-built-app-elf`:
  #!/usr/bin/env bash
  while [ true ]; do
    espflash flash {{espflash_flags}} -p /dev/ttyACM* {{APPFILE}} && exit 0
    sleep 0.5
  done

# Stream serial output, will re-attempt connection if lost.
monitor PORT="/dev/ttyACM*":
  #!/usr/bin/env bash
  while [ true ]; do
    test -c {{PORT}} && just try-monitor {{PORT}}
    # if exit with Ctrl-C, return code will be 130.
    # this should cause a break in the loop
    if [ "$?" -eq 130 ];
    then
      break
    fi
  done

[private]
try-monitor PORT:
  #!/usr/bin/env bash
  echo "# [$(date +%s)] Connected to {{PORT}}"
  while [ true ]; do
    stty -F {{PORT}} speed 115200 cs8 -cstopb -parenb -echo time 3 min 0 2>/dev/null && break
    sleep 0.01
  done

  while [ true ]; do
    cat {{PORT}} 2>/dev/null || break
  done
  echo "# [$(date +%s)] Disconnected from {{PORT}}"


# Find the pasth to the most recently built application file
[private]
find-last-built-app-elf APPNAME="app":
  #!/usr/bin/env bash
  set +eu pipefail
  find ./target/ -maxdepth 3 -name "{{APPNAME}}" -type f -printf "%A@ %p\n" | sort -r | head -n1 | cut -d' ' -f2


# # Experimental! Use cargo-metadata to find the binary filename of the crate before it is built.
# # If it returns more than 1 binary name, this is an error.
# crate-binary-name APPCRATE:
#   #!/usr/bin/env bash
#   set +eu pipefail
#   appdir="$(realpath {{APPCRATE}})"
#   appmanifest="${appdir}/Cargo.toml"
#   test -f "${appmanifest}"
#   bintargetnames=`cargo metadata --format-version 1 --manifest-path "${appmanifest}" | jq '.packages[].targets | map(select(.kind[] == "bin"))[].name'`
#   echo $bintargetnames

###### LINTING ######

cargo-format:
  #!/usr/bin/env bash
  shopt -s globstar 
  cargo fmt --all -- --config-path=rustfmt.toml src/**/*.rs

cargo-clippy:
  #!/usr/bin/env bash
  echo "Hard-coded for esp32s3 chip!" >&2
  cargo clippy --features=esp32s3 --target xtensa-esp32s3-none-elf -- -D warnings --no-deps
