# ulp-baremetal

# Set recipe parameters
chip := "esp32s3"
bin_name := "app"
bin_arch := "riscv32-esp-elf"

# Import common recipes
set allow-duplicate-variables
import "../../binutils.just"
import "../../clippy.just"

default:
  just build

build:
  cargo {{chip}}


